---
ansible_port: 22
ansible_python_interpreter: /usr/bin/python3
ansible_ssh_private_key_file: ~/.ssh/id_omitech
ansible_scp_if_ssh: true

deploy_private_key_file: ~/.ssh/id_omitech_deloy

omitech_base: /home/omitech
