---
- name: Configure hosts
  hosts: omitech.fr
  tasks:
    - name: Deploy SSH public key for ansible_user
      ansible.posix.authorized_key:
        user: "{{ ansible_user }}"
        key: "{{ lookup('file', ansible_ssh_private_key_file + '.pub') }}"
        state: present
